# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
 
pool:
  name: DotNetPool
 
steps:
 
- script: |
    dotnet build HelloDotNet.csproj
  displayName: 'Build HelloDotNet'
 
- script: |
    dotnet test HelloDotNet.csproj
  displayName: 'Run Tests for HelloDotNet'
